var authors = [
  {
    author_no: 1001,
    author_name: "Best Author No 1",
    university: "Best Uni No 1",
    date_of_birth: "1930-01-01",
    h_index: 10,
    gender: "f",
  },
  {
    author_no: 1002,
    author_name: "Best Author No 2",
    university: "Best Uni No 2",
    date_of_birth: "1935-01-01",
    h_index: 15,
    gender: "m",
  },
  {
    author_no: 1003,
    author_name: "Best Author No 3",
    university: "Best Uni No 3",
    date_of_birth: "1940-01-01",
    h_index: 20,
    gender: "f",
  },
  {
    author_no: 1004,
    author_name: "Best Author No 4",
    university: "Best Uni No 4",
    date_of_birth: "1945-01-01",
    h_index: 25,
    gender: "m",
  },
  {
    author_no: 1005,
    author_name: "Best Author No 5",
    university: "Best Uni No 5",
    date_of_birth: "1950-01-01",
    h_index: 30,
    gender: "f",
  },
  {
    author_no: 1006,
    author_name: "Best Author No 6",
    university: "Best Uni No6",
    date_of_birth: "1955-01-01",
    h_index: 32,
    gender: "m",
  },
  {
    author_no: 1007,
    author_name: "Best Author No7",
    university: "Best Uni No7",
    date_of_birth: "1960-01-01",
    h_index: 35,
    gender: "f",
  },
  {
    author_no: 1008,
    author_name: "Best Author No8",
    university: "Best Uni No8",
    date_of_birth: "1965-01-01",
    h_index: 15,
    gender: "m",
  },
  {
    author_no: 1009,
    author_name: "Best Author No9",
    university: "UBest Uni No9",
    date_of_birth: "1970-01-01",
    h_index: 12,
    gender: "f",
  },
  {
    author_no: 1010,
    author_name: "Best Author No10",
    university: "Best Uni No 10",
    date_of_birth: "1975-01-01",
    h_index: 42,
    gender: "f",
  },
  {
    author_no: 1011,
    author_name: "Best Author No11",
    university: "Best Uni No 11",
    date_of_birth: "1980-01-01",
    h_index: 27,
    gender: "f",
  },
  {
    author_no: 1012,
    author_name: "Best Author No12",
    university: "Best Uni No 12",
    date_of_birth: "1971-01-01",
    h_index: 38,
    gender: "f",
  },
  {
    author_no: 1013,
    author_name: "Best Author No13",
    university: "Best Uni No 13",
    date_of_birth: "1977-01-01",
    h_index: 32,
    gender: "f",
  },
  {
    author_no: 1014,
    author_name: "Best Author No14",
    university: "Best Uni No 14",
    date_of_birth: "1983-01-01",
    h_index: 16,
    gender: "m",
  },
  {
    author_no: 1015,
    author_name: "Best Author No15",
    university: "Best Uni No 15",
    date_of_birth: "2000-01-01",
    h_index: 10,
    gender: "f",
  },
];

module.exports = authors;