const papers = [
  {
    paper_id: 01,
    paper_title: "research1",
    conference: "Amsterdam Conference1",
    publish_date: "1920-01-01",
  },
  {
    paper_id: 02,
    paper_title: "research2",
    conference: " Amsterdam Conference2",
    publish_date: "1925-01-01",
  },
  {
    paper_id: 03,
    paper_title: "research3",
    conference: "Amsterdam Conference3",
    publish_date: "1930-01-01",
  },
  {
    paper_id: 04,
    paper_title: "research4",
    conference: "London Conferance1",
    publish_date: "1935-01-01",
  },
  {
    paper_id: 05,
    paper_title: "research5",
    conference: "London Conferance2",
    publish_date: "1940-01-01",
  },
  {
    paper_id: 06,
    paper_title: "research6",
    conference: "London Conferance3",
    publish_date: "1945-01-01",
  },
  {
    paper_id: 07,
    paper_title: "research7",
    conference: "Istanbul Conferance1",
    publish_date: "1950-01-01",
  },
  {
    paper_id: 08,
    paper_title: "research8",
    conference: "Istanbul Conferance2",
    publish_date: "1955-01-01",
  },
  {
    paper_id: 09,
    paper_title: "research9",
    conference: "Istanbul Conferance3",
    publish_date: "1960-01-01",
  },
  {
    paper_id: 10,
    paper_title: "research10",
    conference: "Paris Conference1",
    publish_date: "1965-01-01",
  },
  {
    paper_id: 11,
    paper_title: "research11",
    conference: "Paris Conference2",
    publish_date: "1970-01-01",
  },
  {
    paper_id: 12,
    paper_title: "research12",
    conference: "Paris Conference3",
    publish_date: "1975-01-01",
  },
  {
    paper_id: 13,
    paper_title: "research13",
    conference: "Newyork Con1",
    publish_date: "1980-01-01",
  },
  {
    paper_id: 14,
    paper_title: "research14",
    conference: "Newyork Con2",
    publish_date: "1985-01-01",
  },
  {
    paper_id: 15,
    paper_title: "research15",
    conference: "Newyork Con3",
    publish_date: "1990-01-01",
  },
  {
    paper_id: 16,
    paper_title: "research16",
    conference: "Newyork Con4",
    publish_date: "1995-01-01",
  },
  {
    paper_id: 17,
    paper_title: "research17",
    conference: "Newyork Con5",
    publish_date: "1996-01-01",
  },
  {
    paper_id: 18,
    paper_title: "research18",
    conference: "Roma Con1",
    publish_date: "1997-01-01",
  },
  {
    paper_id: 19,
    paper_title: "research19",
    conference: "Roma Con2",
    publish_date: "1998-01-01",
  },
  {
    paper_id: 20,
    paper_title: "research20",
    conference: "Roma Con3",
    publish_date: "1999-01-01",
  },
  {
    paper_id: 21,
    paper_title: "research21",
    conference: "Roma Con4",
    publish_date: "2000-01-01",
  },
  {
    paper_id: 22,
    paper_title: "research22",
    conference: "Milan Con1",
    publish_date: "2001-01-01",
  },
  {
    paper_id: 23,
    paper_title: "research23",
    conference: "Milan Con2",
    publish_date: "2002-01-01",
  },
  {
    paper_id: 24,
    paper_title: "research24",
    conference: "Milan Con3",
    publish_date: "2003-01-01",
  },
  {
    paper_id: 25,
    paper_title: "research25",
    conference: "Milan Con4",
    publish_date: "2014-01-01",
  },
  {
    paper_id: 26,
    paper_title: "research26",
    conference: "Moscow Con1",
    publish_date: "2015-01-01",
  },
  {
    paper_id: 27,
    paper_title: "research27",
    conference: "Moscow Con2",
    publish_date: "2016-01-01",
  },
  {
    paper_id: 28,
    paper_title: "research28",
    conference: "Moscow Con3",
    publish_date: "2017-01-01",
  },
  {
    paper_id: 29,
    paper_title: "research29",
    conference: "Moscow Con4",
    publish_date: "2018-01-01",
  },
  {
    paper_id: 30,
    paper_title: "research30",
    conference: "Moscow Con5",
    publish_date: "2020-01-01",
  },
];

module.exports = papers;